### ISSUE TITLE
temp folder

### ISSUE THREAD

**Issue by ddomman** [jhawkey/IS_mapper#10]
Hi,
Thanks for the nice software, but there seems to be a bug in that the temp folders are not being deleted after the run by default (at least for me), which then quickly fills up disk space due to the large sam files in there.  

Best,
Daryl

**Comment by jhawkey** [comment]
Hi Daryl,

Thanks for reporting this bug. Can you please provide me with the command that you're running to help me with my testing?

Thanks!

**Comment by ddomman** [comment]
Sorry I realized that I had a bunch of runs fail and the temp folders were the result of this and doesn't seem to be a bug. Thanks for getting back to me quickly, and if I come across anything else (this time I will make sure its real) I'll pass it along.

**Comment by jhawkey** [comment]
I'm glad there are no problems with the script! I'll close this issue now.

**Comment by ddomman** [comment]
Ok this time I really do have a bug with the temp folders not being deleted. The tail of the run output is this:

```
02/23/2016 14:51:56 Index for ISmapper_runs/10868_2#10/ISqueries/ISVch7.fa is already built...
02/23/2016 14:51:56 One or both read files are empty. This is probably due to no copies of the IS of interest being present in this sample. Program quitting.
02/23/2016 14:51:56 ISMapper finished in 5.07131783168 mins.
```
which is great that it doesn't throw an exit code if the IS element isn't found in that particular sample, but the temp folder doesn't get cleaned up in this case.

**Comment by jhawkey** [comment]
Hi Daryl,

Thanks for reporting this. I've noticed this bug myself, and it will be fixed in the next update.

**Comment by jhawkey** [comment]
This fix has now been incorporated into the latest update (v0.1.5)
