### ISSUE TITLE
ISmapper failing at create_typing_out.py

### ISSUE THREAD

**Issue by laurencowley** [jhawkey/IS_mapper#17]
Hi, I am running IS_mapper on multiple IS references in fasta format but it keeps failing on the 4th reference no matter which one. I get this error:
05/04/2016 10:33:42 Running: create_typing_out.py --intersect H111960548processed_Ss046_IS1397_IS3_EC_intersect.bed --closest H111960548processed_Ss046_IS1397_IS3_EC_closest.bed --left_bed H111960548processed_5_Ss046_IS1397_IS3_EC_merged.sorted.bed --right_bed H111960548processed_3_Ss046_IS1397_IS3_EC_merged.sorted.bed --left_unpaired H111960548processed_Ss046_IS1397_IS3_EC_left_unpaired.bed --right_unpaired H111960548processed_Ss046_IS1397_IS3_EC_right_unpaired.bed --seq ../IS_elements/IS1397_IS3_EC.fasta --ref /home/lauren/snapperdb/reference_genomes/Ss046.gb --temp /phengs/hpc_projects/lauren/EIEC/IS_mapper/H111960548processed_IS1397_IS3_EC_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output H111960548processed_IS1397_IS3_EC --igv 0 --chr_name not_specified
Traceback (most recent call last):
  File "/phengs/hpc_software/ismapper/0.1.3/scripts/create_typing_out.py", line 537, in <module>
    main()
  File "/phengs/hpc_software/ismapper/0.1.3/scripts/create_typing_out.py", line 519, in main
    for key in sorted_keys[:,0]:
UnboundLocalError: local variable 'sorted_keys' referenced before assignment
Traceback (most recent call last):
  File "/phengs/hpc_software/ismapper/0.1.3/scripts/ismap.py", line 652, in <module>
    main()
  File "/phengs/hpc_software/ismapper/0.1.3/scripts/ismap.py", line 640, in main
    '--max_range', args.max_range, '--output', sample + '_' + query_name, '--igv', igv_flag, '--chr_name', args.chr_name], shell=True)
  File "/phengs/hpc_software/ismapper/0.1.3/scripts/ismap.py", line 99, in run_command
    raise CommandError({"message": message})
__main__.CommandError: {'message': "Command 'create_typing_out.py --intersect H111960548processed_Ss046_IS1397_IS3_EC_intersect.bed --closest H111960548processed_Ss046_IS1397_IS3_EC_closest.bed --left_bed H111960548processed_5_Ss046_IS1397_IS3_EC_merged.sorted.bed --right_bed H111960548processed_3_Ss046_IS1397_IS3_EC_merged.sorted.bed --left_unpaired H111960548processed_Ss046_IS1397_IS3_EC_left_unpaired.bed --right_unpaired H111960548processed_Ss046_IS1397_IS3_EC_right_unpaired.bed --seq ../IS_elements/IS1397_IS3_EC.fasta --ref /home/lauren/snapperdb/reference_genomes/Ss046.gb --temp /phengs/hpc_projects/lauren/EIEC/IS_mapper/H111960548processed_IS1397_IS3_EC_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output H111960548processed_IS1397_IS3_EC --igv 0 --chr_name not_specified' failed with non-zero exit status: 1"}
Thanks!

**Comment by jhawkey** [comment]
Hi Lauren,

Thanks for reporting this issue. Can you please email me your reads and references so I can run ISMapper on my end and debug for you? My email address is at the start of the readme file.

**Comment by ksanjeetsinha** [comment]
Hi,
I am also getting the similar error in the execution of "create_typing_out.py". I have been using a single fasta file as a query.
IS_mapper is working perfectly fine with the other data set.

Please Suggest! 
Kumar

**Comment by jhawkey** [comment]
Hi @ksanjeetsinha,

Are you able to send me the input files being provided to the create_typing_out command? These are the same files as found in issue #27. This should be the intersect.bed file, closest.bed file, left.bed file, right.bed file, left_unpaired.bed file, right_unpaired.bed file and the IS query in fasta format. You should be able to attach them here in github.

**Comment by luciagrami** [comment]
Hi,
I am having the same issue.
Taking your advice I am attaching the files and maybe you could help me.




[files.zip](https://github.com/jhawkey/IS_mapper/files/1733139/files.zip)
