### ISSUE TITLE
Fi

### ISSUE THREAD

**Issue by areejalsheikh** [jhawkey/IS_mapper#19]
Hi, 

ISMapper is great - great job! 

I found out that it gives off "failure" message when the IS is not found anywhere in the genome. Here is the message: 

`ismap.ismap.CommandError: {'message': "Command 'bedtools merge -d 100 -i /home/areej/SIPG/IS/typing-method/edited_gbk_all_strains_IS_IS981_2/141_5_XXXXXX_23072016_withCDS_XXXXXX_1339-1340_IS981_finalcov.bed > /home/areej/SIPG/IS/typing-method/edited_gbk_all_strains_IS_IS981_2/141_5_XXXXXX_23072016_withCDS_XXXXXX_1339-1340_IS981_merged.sorted.bed' failed with non-zero exit status: 1"}`

It works with all other strains just fine. I tried running the same strain which gives the 'failing' message with another IS, and it had no issues at all. An explicit message that says "no hits found" would be nice :)

Thanks,
Areej

**Comment by jhawkey** [comment]
Thanks Areej!

This is an issue I'm aware of and is listed in my things to do for the next update. But thank you for brining it up! It should be addressed in the next version.

**Comment by jhawkey** [comment]
This fix has now been incorporated into the latest update (v0.1.5)
