### ISSUE TITLE
Identify insertion sites

### ISSUE THREAD

**Issue by adam-lab** [jhawkey/IS_mapper#21]
Hello. Thanks for sharing this helpful tool (IS_mapper). I am exploring it's use for a project, and got some ambiguous results on the preliminary data, and I'm trying to figure out what's going on. My suspicion is that my target genome has had some rearrangements or large indels with respect to my reference genome -- as a result, some insertion events cannot be detected by IS_mapper. I'd like to test whether it is even possible to identify my favorite IS element by checking if its insertion site (AYTAG) can be detected. Conceptually, it seems straightforward to select reads for mapping based on the presence of the insertion site rather than the presence of the the IS element; however, I have not looked into the code to see what would be involved. Before I mess around with this approach, I thought I'd ask if this issue has come up before and if there are any plans to incorporate a feature like this.  Thanks! -adam

**Comment by jhawkey** [comment]
Hi Adam,

Currently this feature isn't implemented and I have no plans to incorporate it in the near future. Feel free to mess around with the code, if you manage to find a good solution and would like it incorporated into ISMapper, we can certainly look into that!
