### ISSUE TITLE
Problem with gbk file at the compiled_table.py stage.

### ISSUE THREAD

**Issue by rahimrajwani** [jhawkey/IS_mapper#24]
Hi !
IS-mapper seems a great tool!
I am trying to map insertion sequence against this https://www.ncbi.nlm.nih.gov/nuccore/50953765 reference. But it fails:

Building a new DB, current time: 02/17/2017 22:53:28
New DB name:   /home/rahim/Downloads/IS6110.fasta
New DB title:  IS6110.fasta
Sequence type: Nucleotide
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1 sequences in 0.00202703 seconds.
/home/rahim/Downloads/ERR071082_IS6110_temp/CDC1551.fasta.bwt
[bwa_index] Pack FASTA... 0.05 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 1.68 seconds elapse.
[bwa_index] Update BWT... 0.03 sec
[bwa_index] Pack forward-only FASTA... 0.03 sec
[bwa_index] Construct SA from BWT and Occ... 0.78 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index /home/rahim/Downloads/ERR071082_IS6110_temp/CDC1551.fasta
[main] Real time: 2.751 sec; CPU: 2.564 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 3832 sequences (130795 bp)...
[M::mem_process_seqs] Processed 3832 reads in 0.092 CPU sec, 0.096 real sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -t 1 /home/rahim/Downloads/ERR071082_IS6110_temp/CDC1551.fasta /home/rahim/Downloads/ERR071082_IS6110_temp/ERR071082_IS6110_LeftFinal.fastq
[main] Real time: 0.122 sec; CPU: 0.104 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 4013 sequences (137051 bp)...
[M::mem_process_seqs] Processed 4013 reads in 0.092 CPU sec, 0.098 real sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -t 1 /home/rahim/Downloads/ERR071082_IS6110_temp/CDC1551.fasta /home/rahim/Downloads/ERR071082_IS6110_temp/ERR071082_IS6110_RightFinal.fastq
[main] Real time: 0.122 sec; CPU: 0.100 sec
[samopen] SAM header is present: 1 sequences.
[samopen] SAM header is present: 1 sequences.
left index
2 - THIS SHOULDN'T HAPPEN!
right index
4
left position: 1592
right position: 1594
Traceback (most recent call last):
  File "/usr/local/bin/create_typing_out.py", line 543, in <module>
    main()
  File "/usr/local/bin/create_typing_out.py", line 311, in main
    novel_hit(x_L, y_L, x_R, y_R, x, y, genbank, args.ref, args.cds, args.trna, args.rrna, '-' + info[6], orient, feature_count, region, results, genbank.features, feature_list, unpaired=False)
  File "/usr/local/bin/create_typing_out.py", line 142, in novel_hit
    gene_left, gene_right = get_flanking_genes(features, feature_list, x, y, cds, trna, rrna, len(genbank.seq))
  File "/usr/local/bin/compiled_table.py", line 338, in get_flanking_genes
    left_feature = features[left_feature_index]
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/local/bin/ismap", line 9, in <module>
    load_entry_point('ISMapper==0.1.4', 'console_scripts', 'ismap')()
  File "/usr/local/lib/python2.7/dist-packages/ismap/ismap.py", line 648, in main
    '--max_range', args.max_range, '--output', current_dir + sample + '_' + query_name, '--igv', igv_flag, '--chr_name', args.chr_name], shell=True)
  File "/usr/local/lib/python2.7/dist-packages/ismap/ismap.py", line 101, in run_command
    raise CommandError({"message": message})
ismap.ismap.CommandError: {'message': "Command 'create_typing_out.py --intersect /home/rahim/Downloads/ERR071082_CDC1551_IS6110_intersect.bed --closest /home/rahim/Downloads/ERR071082_CDC1551_IS6110_closest.bed --left_bed /home/rahim/Downloads/ERR071082_5_CDC1551_IS6110_merged.sorted.bed --right_bed /home/rahim/Downloads/ERR071082_3_CDC1551_IS6110_merged.sorted.bed --left_unpaired /home/rahim/Downloads/ERR071082_CDC1551_IS6110_left_unpaired.bed --right_unpaired /home/rahim/Downloads/ERR071082_CDC1551_IS6110_right_unpaired.bed --seq IS6110.fasta --ref CDC1551.gbk --temp /home/rahim/Downloads/ERR071082_IS6110_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /home/rahim/Downloads/ERR071082_IS6110 --igv 0 --chr_name not_specified' failed with non-zero exit status: 1"}

Could you spot out any problem with the reference here? I have already tried the same set of reads against another reference and it works fine. Many thanks in advance.

**Comment by jhawkey** [comment]
This is an interesting error. There seems to be a problem with the pairing of left and right flanks to create a hit. To properly diagnose this error I'll need access to the reads, IS query you're using, and the reference. 
I can access the reference genome from the link you've provided - is the IS6110 sequence taken from ISFinder? If so, I'll just need you to send me the reads, unless they are already publicly available for download, in which case you can just send me the link to the reads instead.

**Comment by rahimrajwani** [comment]
Actually, I solved it. The Genbank record I downloaded was not complete. It
did not contain reverse competent and some sequence features. Correctly
downloading the complete Genbank record solved the problem.

Thanks very much for your response.

**Comment by jhawkey** [comment]
Great! Glad that you managed to fix it.
