### ISSUE TITLE
pip install without cloning repo....

### ISSUE THREAD

**Issue by andersgs** [jhawkey/IS_mapper#25]
Hi Jane.

Thank you for taking up the pull request. Hopefully useful.

You could add the README that people can install directly from GitHub:

`pip install git+https://github.com/jhawkey/IS_mapper`

If a user wants to install locally:

`pip install --user git+https://github.com/jhawkey/IS_mapper`

If someone wants to install a particular release or tag:

`pip install git+https://github.com/jhawkey/IS_mapper@my_tag`

Cheers.

Anders.

**Comment by jhawkey** [comment]
Updated the readme!
