### ISSUE TITLE
Need help concerning the IS queries 

### ISSUE THREAD

**Issue by ldeblais** [jhawkey/IS_mapper#26]
Hi, 

I am trying to use the ISmapper program with my illumina short read sequence data. 
Let me explain my project really fast: 
- The aim of my project is to identify the potential target(s) of several drug into S. Typhimurium LT2. 
- To do that I created a large library of mutant using the Ez::Tn5 transposome kit (random mutation into the chromosome) and changed my mutants with lethal dose of my drugs. 
- I extracted the DNA of the mutants able to grow into a lethal dose and amplified the outside of the transposon in order to identify the site of insertion (= drug target).

What I have: 
- The short read sequence data for both left and right side of the insertion site (in two separated fasta files)
- The reference genome of S. Typhimurium LT2 

My problem: 
**- How can I get the IS queries ?** I have no idea where the transposon was inserted in the genome unless I am starting the mapping process. 
 
I tried to understand how to have the  Is queries via your GitHub page and the publication, but I am still very confuse. 
  
Thank you very much for your help. 

Ps: I really like your publication about the ISmapper.

**Comment by jhawkey** [comment]
Hi ldeblais,

I'm not sure your data is suitable for ISMapper. ISMapper requires short reads from the region spanning the transposon, as well as the flanking section. Usually, the entire genome is sequenced using paired end short reads, and these reads are used as input for ISMapper.

From what you've described here, it sounds like you don't have the appropriate input data to use ISMapper.

Thanks for your interest!
