### ISSUE TITLE
right merged bed file empty causes create_typing_out.py to fail

### ISSUE THREAD

**Issue by laurencowley** [jhawkey/IS_mapper#29]
Hi Jane
Sorry its me again!
`09/29/2017 17:44:50 Running: closestBed -a /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_left_Ss046_IS1397_IS3_EC_merged.sorted.bed -b /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_right_Ss046_IS1397_IS3_EC_cov_merged.sorted.bed -d > /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_left_unpaired.bed
09/29/2017 17:44:50 Running: closestBed -a /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_left_Ss046_IS1397_IS3_EC_cov_merged.sorted.bed -b /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_right_Ss046_IS1397_IS3_EC_merged.sorted.bed -d > /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_right_unpaired.bed
09/29/2017 17:44:50 Running: create_typing_out.py --intersect /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_intersect.bed --closest /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_closest.bed --left_bed /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_left_Ss046_IS1397_IS3_EC_merged.sorted.bed --right_bed /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_right_Ss046_IS1397_IS3_EC_merged.sorted.bed --left_unpaired /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_left_unpaired.bed --right_unpaired /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_right_unpaired.bed --seq /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/IS1397_IS3_EC.fasta --ref /home/lauren/snapperdb/reference_genomes/Ss046.gb --temp /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC --igv 0 --chr_name not_specified
Traceback (most recent call last):
  File "/phengs/hpc_software/ismapper/0.1.5/scripts/create_typing_out.py", line 543, in <module>
    main()
  File "/phengs/hpc_software/ismapper/0.1.5/scripts/create_typing_out.py", line 339, in main
    y_R = int(info[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/phengs/hpc_software/ismapper/0.1.5/scripts/ismap.py", line 754, in <module>
    main()
  File "/phengs/hpc_software/ismapper/0.1.5/scripts/ismap.py", line 743, in main
    '--max_range', args.max_range, '--output', current_dir + sample + '_' + query_name, '--igv', igv_flag, '--chr_name', args.chr_name], shell=True)
  File "/phengs/hpc_software/ismapper/0.1.5/scripts/ismap.py", line 150, in run_command
    raise CommandError({"message": message})
__main__.CommandError: {'message': "Command 'create_typing_out.py --intersect /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_intersect.bed --closest /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_closest.bed --left_bed /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_left_Ss046_IS1397_IS3_EC_merged.sorted.bed --right_bed /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_right_Ss046_IS1397_IS3_EC_merged.sorted.bed --left_unpaired /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_left_unpaired.bed --right_unpaired /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_right_unpaired.bed --seq /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/IS1397_IS3_EC.fasta --ref /home/lauren/snapperdb/reference_genomes/Ss046.gb --temp /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC --igv 0 --chr_name not_specified' failed with non-zero exit status: 1"}
`
With some investigation I've found that the right merged bed file is empty. and this crashes the program. Is there a way around this?

**Comment by jhawkey** [comment]
Hi Lauren,

I'm not sure why it's crashing the program - an empty bed file should just return an exit status and state that there are no IS found (because it can't pair things up if there are no reads on the right flank of the IS).

I'm currently working on version 2, which I hope will fix many of these types of errors.

In the meantime, if you like you can attach here all the input files that 'create_typing_out' requires (just make the extensions .txt to upload them), and I can take a look.

The files I need are listed in the call here:
```reate_typing_out.py --intersect /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_intersect.bed --closest /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_closest.bed --left_bed /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_left_Ss046_IS1397_IS3_EC_merged.sorted.bed --right_bed /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_right_Ss046_IS1397_IS3_EC_merged.sorted.bed --left_unpaired /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_left_unpaired.bed --right_unpaired /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_right_unpaired.bed --seq /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/IS1397_IS3_EC.fasta --ref /home/lauren/snapperdb/reference_genomes/Ss046.gb --temp /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC_temp/ --cds locus_tag gene product --trna locus_tag product --rrna locus_tag product --min_range 0.2 --max_range 1.1 --output /phengs/hpc_storage/home/lauren/scripts/ismapper_bash/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_IS1397_IS3_EC --igv 0 --chr_name not_specified```

**Comment by laurencowley** [comment]
[152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_left_Ss046_IS1397_IS3_EC_merged.sorted.bed.txt](https://github.com/jhawkey/IS_mapper/files/1395216/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_left_Ss046_IS1397_IS3_EC_merged.sorted.bed.txt)
[152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_left_unpaired.bed.txt](https://github.com/jhawkey/IS_mapper/files/1395229/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_left_unpaired.bed.txt)
[152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_right_unpaired.bed.txt](https://github.com/jhawkey/IS_mapper/files/1395230/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_right_unpaired.bed.txt)

[152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_closest.bed.txt](https://github.com/jhawkey/IS_mapper/files/1395254/152654_H14186079401-1.escherichia-coli-typing.2-0-1.processed_Ss046_IS1397_IS3_EC_closest.bed.txt)

This could also be to do with me running a multi fasta of a lot of different IS elements?
[Ss046.gb.txt](https://github.com/jhawkey/IS_mapper/files/1395276/Ss046.gb.txt)
[IS1397_IS3_EC.fasta.txt](https://github.com/jhawkey/IS_mapper/files/1395289/IS1397_IS3_EC.fasta.txt)
