### ISSUE TITLE
Problems with references consisting of more than one chromosome

### ISSUE THREAD

**Issue by bioinfo-bfr** [jhawkey/IS_mapper#33]
Hey, 

I just saw that the ISmapper has problems with .gbk files of Bacteria that have more than one chromosome. In this case only the first chromosome is considered as reference. Is there a way to work with ISmapper without seperating the .gbk files? Would be also of interest when the reference genome is not complete and exists only as a draft genome with several contigs.

Thanks!

**Comment by jhawkey** [comment]
Yes, this is a known issue. I am currently working on a version 2 that will allow the use of multi entry genbank files.

Currently your only option is to concatenate the entries, or run each chromosome separately!
