### ISSUE TITLE
R1 and R2 file extensions not being paired properly

### ISSUE THREAD

**Issue by jhawkey** [jhawkey/IS_mapper#4]
Trying with eg: isolateA_R1.trimmed.paired.fastq.gz and just isolateA_R1.fastq.gz

**Comment by bluefish171** [comment]
isolateA_R1.fastq.gz and isolateA_R2.fastq.gz still throw exception
isolateA_1.fastq.gz and isolateA_1.fastq.gz is OK!

**Comment by jhawkey** [comment]
thanks bluefish.

I looked into this - R1 and R2 reads are being paired correctly, but they need to be in the MiSeq format samplename_S1_L001_[R1]_001. If the extension is just _R1 or _R2, then the designations for forward and reverse read need to be supplied by `--forward R1 --reverse R2`.
