### ISSUE TITLE
New release for conda

### ISSUE THREAD

**Issue by rpetit3** [jhawkey/IS_mapper#40]
Hi Jane, 

When you have some time, could you create a new release (maybe v.2.0.1?) to include the changes in PR https://github.com/jhawkey/IS_mapper/pull/38? Bioconda will then automatically update the ISMapper install.

No rush though, I have a temporary conda install with the changes setup at https://anaconda.org/rpetit3/ismapper

Thanks again for a great tool!
Robert

**Comment by jhawkey** [comment]
Hi Robert,

Thanks for the bugfix, and I've now finally gotten around to doing a release with this change incorporated, so hopefully bioconda will now update.

Jane

**Comment by rpetit3** [comment]
Fun stuff! Thank you very much!

**Comment by rpetit3** [comment]
Hi Jane, 

Would it be possible to change the tag for 2.0.1 to "v2.0.1"? I think the missing "v" cause the auto bump on Bioconda to miss 2.0.1.

If you can't change it, I'll go ahead and change the recipe on Bioconda.

Thanks!

**Comment by jhawkey** [comment]
Done (I hope!) I updated the tag on the release, hopefully that will now propagate out to bioconda.
