### ISSUE TITLE
run_commands.CommandError

### ISSUE THREAD

**Issue by swilde1** [jhawkey/IS_mapper#41]
After installing IS Mapper and its dependencies/other required programs, I tried running the test scripts. The first one worked fine without any errors, but when I go to run the actual ismap test command (just copied/pasted into Terminal), it basically says that "bwa" doesn't exist (attached photo). I've verified that BWA is in fact installed and the executable file is in its respective folder. Any ideas on what I can do to make BWA run in conjunction with this program? (Full disclosure: I'm very new at programming/using Python, so I know close to nothing about troubleshooting).

![IMG_9267](https://user-images.githubusercontent.com/61064421/74561734-27ef2100-4f37-11ea-8ac4-64683ce5674f.jpg)

**Comment by rpetit3** [comment]
Hi @swilde1

Have you tried the conda instal for ISMapper?

Cheers

**Comment by jhawkey** [comment]
Hi @swilde1,

I second @rpetit3 suggestion that you should maybe try the conda install, as that will take care of all the dependencies for you. You can find out more about conda here: https://docs.conda.io/en/latest/

The command for installing ISMapper via conda can be found in the README, in the installation section.

Based on your issue, it sounds like the BWA executable isn't in your PATH. You might need to edit your PATH to include the directory where you've put the BWA executable. This blogpost seems to have a decent explanation of what your PATH is and how you can edit it, in case you aren't familiar https://opensource.com/article/17/6/set-path-linux
