### ISSUE TITLE
BioAlphabet is obsolete

### ISSUE THREAD

**Issue by joshuakirsch** [jhawkey/IS_mapper#44]
Hi,

I am trying to use ISMapper but testing the installation gives this error:
ismap --version
Traceback (most recent call last):
  File "/Users/duerkoplab/opt/miniconda3/envs/ismapper-bioconda/bin/ismap", line 7, in <module>
    from ismap import main
  File "/Users/duerkoplab/opt/miniconda3/envs/ismapper-bioconda/bin/ismap.py", line 12, in <module>
    from mapping_to_query import map_to_is_query
  File "/Users/duerkoplab/opt/miniconda3/envs/ismapper-bioconda/bin/mapping_to_query.py", line 6, in <module>
    from Bio.Alphabet import generic_dna
  File "/Users/duerkoplab/opt/miniconda3/envs/ismapper-bioconda/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by jhawkey** [comment]
Thanks for alerting me to this! This appears to be a very recent change in BioPython. I've made a note that I need to update the code to be compatible with the newest version, but it will take me a few weeks to get to that. In the interim, you should just update your conda environment to use an older version of BioPython, and that should fix the issue you're currently having.

**Comment by joshuakirsch** [comment]
Thank you so much for your resposne. I'm very very new to conda and terminal in general. Could you possibly provide the code I would need to update biopython to an older version in a conda enviorment?

Thanks,
Josh

**Comment by jhawkey** [comment]
Yep, no problem, it's nice and straightforward.

Load up your conda environment that contains ISMapper, and then run
```conda install biopython=1.77```

conda will let you know that it's editing a package you've installed with a lower version, just type `y` to proceed and you'll be good to go.

**Comment by soominlll** [comment]
Hi,
I downgrand the version of biopython to v.1.77.
And tried to test using the test data you provided.
And found that it showed issue #38 again.
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs

I used ismpper ver. 2.0.1 to solve this problem (with biopython v. 1.77) but couldn't solve it
would you help me please?

Thank you.

**Comment by peterjc** [comment]
This looks to have been fixed in v2.0.2, so this can be closed now I think?

**Comment by jhawkey** [comment]
Yep, it is, closing now.
