### ISSUE TITLE
No regex found for (*has my fastq read names*), unable to pair reads

### ISSUE THREAD

**Issue by snehamurthy21** [jhawkey/IS_mapper#45]
hi

Im facing an issue while running ismapper, with the following error :

No regex found for LVP-7-g-DNA_S5_L004_R1_001_val_1.fq (LVP-7-g-DNA_S5_L004_R1_001_val_1.fq), unable to pair reads

this is the command i have used : `ismap --reads LVP-7-g-DNA_S5_L004_R1_001_val_1.fq LVP-7-g-DNA_S5_L004_R2_001_val_2.fq --queries PROKKA_10062020.fna --reference PROKKA_10062020.gbk --output_dir .`

Please help me out with a solution

**Comment by idolawoye** [comment]
I am having similar issues too. 

`ismap --reads ERR2383618_1.fq.gz ERR2383618_2.fq.gz --queries IS6110_query.fasta --reference ../MTB_ancestor_reference.fasta --output_dir ISmapping`

> Traceback (most recent call last):
File "/home/idowu/anaconda3/envs/ismapper-bioconda/bin/ismap", line 10, in <module> sys.exit(main())
File "/home/idowu/anaconda3/envs/ismapper-bioconda/bin/ismap.py", line 168, in main read_groups = read_grouping.group_reads(args.reads)
File "/home/idowu/anaconda3/envs/ismapper-bioconda/bin/read_grouping.py", line 96, in group_reads
read_map = create_prefix_map(short_read_fps)
File "/home/idowu/anaconda3/envs/ismapper-bioconda/bin/read_grouping.py", line 139, in create_prefix_map
raise ValueError('No regex found for %s (%s), unable to pair reads' % (read_fp.name, read_fp))
ValueError: No regex found for ERR2383618_1.fq.gz (ERR2383618_1.fq.gz), unable to pair reads

Kindly assist with this error

**Comment by idolawoye** [comment]
> hi
> 
> Im facing an issue while running ismapper, with the following error :
> 
> No regex found for LVP-7-g-DNA_S5_L004_R1_001_val_1.fq (LVP-7-g-DNA_S5_L004_R1_001_val_1.fq), unable to pair reads
> 
> this is the command i have used : `ismap --reads LVP-7-g-DNA_S5_L004_R1_001_val_1.fq LVP-7-g-DNA_S5_L004_R2_001_val_2.fq --queries PROKKA_10062020.fna --reference PROKKA_10062020.gbk --output_dir .`
> 
> Please help me out with a solution

I was able to sort the issue out. You will have to rename your FASTQ files extension from fq to fastq
