### ISSUE TITLE
x co-ordinate = -1

### ISSUE THREAD

**Issue by SamuelGreenrod** [jhawkey/IS_mapper#46]
I've run ISMapper using short reads on a reference, using IS elements identified in the reference using ISEScan as the queries. Quite a lot of the novel insertion sites have very large gaps (> 1mb), largely due to the x co-ordinates all starting at -1. What does it mean for x to start here and why is it reported as novel despite the gap being so big? Thanks.

**Comment by jhawkey** [comment]
Hi,

Are you able to provide me with some example short read data and your reference queries? This sounds like a very strange error, I'm not sure why all the x coordinates would start at -1.

**Comment by SamuelGreenrod** [comment]
Hi, 

I've sent you an email with the problem outlined and some data hopefully to replicate it - sorry for the late response!

**Comment by SamuelGreenrod** [comment]
I've had a play around and have tried changing the parameters and references and think I have solved it. When running with a reference assembly with ISs removed (as described in https://doi.org/10.1371/journal.pgen.1008931), for ISs that are flanked by other ISs, the flanking reads will have nothing in the reference to map to. This means that in my case, if an IS is adjacent to another IS, flanking reads on one side aren't able to map to the reference, hence the -1 coordinate. I've confirmed this by running it with a complete reference assembly with no ISs removed and the coordinates are fine.

I think it might be good to include a short bit in the GitHub advising whether ISs should be removed from references before running (as you did in your paper), and the potential benefits and pitfalls that might arise from this! I'll continue with IS-containing references from now. Cheers!

**Comment by jhawkey** [comment]
Hi Samuel,

Glad you managed to figure it out! Indeed that is one of the shortcomings of short read data - it's very difficult to detect IS using this method if they are inserted within other IS or next to them. I'll close this comment now, and look at adding some more information to the readme about this use case.
