### ISSUE TITLE
Nature of Biopython incompatibility

### ISSUE THREAD

**Issue by verdurin** [jhawkey/IS_mapper#48]
Hello

I am looking at including `ISMapper` in `EasyBuild`, for use on HPC clusters.

I wondered about the notice in https://github.com/jhawkey/IS_mapper#requirements regarding incompatibility with `Biopython` versions newer than `1.77` - what is the exact problem here?

And does it still apply?

**Comment by jhawkey** [comment]
The issue with newer versions of BioPython was the removal of Bio.Alphabet, which ISMapper used to load. However as of v2.0.2 (released July 13 of this year), Bio.Alphabet is no longer imported and so ISMapper should now be compatible with later versions of BioPython. I will update the requirements section of the readme.

Thanks!
