### ISSUE TITLE
Accept multi-FASTA IS input

### ISSUE THREAD

**Issue by rrwick** [jhawkey/IS_mapper#9]
ISMapper crashes if I give it a multi-FASTA file for the `--queries` argument.  It would be nice if it could accept such files and search for each IS in the file.  Thanks!

**Comment by jhawkey** [comment]
Multiple query sequences can now be supplied by a multifasta file (v0.1.5). However, this means that you are now no longer able to supply multiple fasta files to the command line - they need to be in a single fasta.
